{% set name = "bashlex" %}
{% set version = "0.14" %}
{% set sha256 = "5a92e0900b7a91de93a338b3fae651adc2b6a0e9656972b9e2ed3afd9c492ffd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - enum34  # [py<34]

test:
  imports:
    - bashlex

about:
  home: https://github.com/idank/bashlex
  license: GPL-3.0
  license_family: GPL
  # License file added manually so far:
  # https://github.com/idank/bashlex/issues/27
  # https://github.com/conda-forge/staged-recipes/pull/4401
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/idank/bashlex
  summary: 'Python parser for bash'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
