{% set name = "bashlex" %}
{% set version = "0.15" %}
{% set sha256 = "fe539cf9eba046f60a8d32eda2a28e9dccdd06cb4b9f5089ec658348ea53a6dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - enum34  # [py<34]

test:
  imports:
    - bashlex

about:
  home: https://github.com/idank/bashlex
  license: GPL-3.0
  license_family: GPL
  # License file added manually so far:
  # https://github.com/idank/bashlex/issues/27
  # https://github.com/conda-forge/staged-recipes/pull/4401
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  dev_url: https://github.com/idank/bashlex
  summary: Python parser for bash

extra:
  recipe-maintainers:
    - sebastian-luna-valero
