{% set name = "bashlex" %}
{% set version = "0.17" %}
{% set sha256 = "2aed062438e10ee89742bc80969793cd9ee4a3fab6cfb2365e43731aabd21010" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - enum34  # [py<34]

test:
  imports:
    - bashlex

about:
  home: https://github.com/idank/bashlex
  license: GPL-3.0-only
  license_family: GPL
  # License file added manually so far:
  # https://github.com/idank/bashlex/issues/27
  # https://github.com/conda-forge/staged-recipes/pull/4401
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  dev_url: https://github.com/idank/bashlex
  summary: Python parser for bash

extra:
  recipe-maintainers:
    - sebastian-luna-valero
