appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: dHdBXK8xlSk+FxraFwlWGrJct19l37QFN3aQT1ITl1iuwcpOjXO8rwSOCIiUIEP9LThceezNVdFQBbQCMJ7Scx5NhCvf2pe1OQ7zm8IxsZGq5bJlx8iAhHmcJhdX3Dfs/2WruW1OxleBcu3ksiJ8J7mbUv8hFzC0UdkH0P9rNfo7qWrA6EuUDESDXvGINvNA+WXnzSdSdfz6xlP/D5e5TSoxz7mNa5ZYiWusU7SlysPeRGz4LFmq4ALJVCw+JtbQfLUDSHB541GbSCuW6w4pzHtR/UQdaSWsyyrRzgXKS/T4KDFt2xqc3eGCtBl2wAoCp9EYl4TrRsyGLp3wHYx3JbTgpyMuVWREVUNd0Av+7A0Z+JVCDVerVn32wqYy2hjsavrSKuBVnjDVMTkZa/hKRhTK3a8NCLbmulyGAsVUDp8zyXgIS6t1onEb1ZFJWEsAud5tgAFp51jY0m04oX7TZCCXCYh9Bi5ICCY5Dv+w7ebZYSatB7iFqBGg98hfVrpOzPZ00Jcu2RjML5K5GQIOBE+6+omS86mk7FkAc/slK6SDjZ+6sm9KhTA0Y/ZDv0R7JjfSYL+YLEwKLvLXdp3nz2wvD2Ig2hgdyVlSxRuthZ6yESw+aNHvIxOA9rmfEbFX1rQsiHPiAMoRj+NfiUNARRwC4JIgDqtZjp8rV3Cp0iI=}
provider:
  win: azure
conda_forge_output_validation: true
